### Configurations from config server
discovery-service-user:
  server:
    hostname: localhost
    port: 8010

#
kafka-user:
  bootstrap-servers: 192.168.0.125:29092,192.168.0.125:39092,192.168.0.125:49092

#
app:
  gateway:
    api-prefix: /api/v1
  frontend:
    origin: "http://192.168.0.190:5173"
###


spring:
  application:
    name: realtime-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_USER}:${CONFIG_SERVER_PASSWORD}@${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8012}



  kafka:
    bootstrap-servers: ${kafka-user.bootstrap-servers}
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.mrshoffen.tasktracker.commons.kafka.event.*"

server.port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://${discovery-service-user.server.hostname}:${discovery-service-user.server.port}/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


